# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: questions_db
    image: 'postgres:14.4'
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: frank # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: postgres # The PostgreSQL default database (automatically created at first launch)
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local