[package]
name = "handle-errors"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = { version = "0.3" }
sqlx = { version = "0.5" }
reqwest = { version = "0.11" }
tracing = { version = "0.1.35", features = ["log"] }
reqwest-middleware = { version = "0.1.1" }

